version: '3.1'

services:
  web-selenium:
    image: ahadalichowdhury/youtube-summarizer:latest 
    container_name: youtube-summarizer:latest
    shm_size: '2gb'
    build:
      context: . 
    ports:
      - 5000:5000