version: '3.8'
services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env  # Add this line to specify the .env file
    volumes:
      - .:/app
    restart: always
